version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in testing ...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...hhhhhh
      - aws --version
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...     
      - docker build -t ecs-test:latest .
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws s3 cp Dockerfile s3://sopradevtraining/
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker tag ecs-test:latest 114292955443.dkr.ecr.us-east-1.amazonaws.com/build_spec:latest
      - docker push 114292955443.dkr.ecr.us-east-1.amazonaws.com/build_spec:latest
